import { Inject, Injectable } from '@nestjs/common';
import { z } from 'zod';
import { Database, Sql } from '../database';
import { now, parse, dueAt, money, amountSchema, currencySchema } from '../domain';
import { RatesService } from '../rates';
import { FinanceService } from '../finance';
const resources=['earnings','expenses','shopping','budgets','splits','movements','allocations'] as const;
const querySchema=z.object({resource:z.enum(resources),from:z.iso.date().optional(),to:z.iso.date().optional(),q:z.string().max(120).optional(),amount_min:z.coerce.number().min(0).optional(),amount_max:z.coerce.number().min(0).optional(),page:z.number().int().min(1).max(10000).default(1),project_id:z.number().int().positive().optional(),recurring:z.boolean().optional()}).strict();
export const FINANCIAL_TOOL={name:'consultar_finanzas',description:'Consulta registros o totales históricos del usuario autenticado. Todas las páginas tienen totales completos sobre el filtro, nunca sumar solamente la página. Usa filtros de fecha, monto y texto para preguntas específicas. Devuelve cobertura y páginas pendientes. Los proyectos se incluyen salvo que se indique project_id; separa sus importes de las cuentas personales. Si solo necesitas un total, conteo o promedio (sin ver movimientos concretos), usa resumir_finanzas en vez de esta: es más liviana y no gasta contexto listando filas, especialmente en historiales largos.',parameters:{type:'OBJECT',properties:{resource:{type:'STRING',enum:[...resources]},from:{type:'STRING',description:'Fecha inicial YYYY-MM-DD'},to:{type:'STRING',description:'Fecha final YYYY-MM-DD'},q:{type:'STRING',description:'Texto en descripción o etiquetas'},amount_min:{type:'NUMBER',description:'Solo montos mayores o iguales a este valor'},amount_max:{type:'NUMBER',description:'Solo montos menores o iguales a este valor'},page:{type:'INTEGER'},project_id:{type:'INTEGER'},recurring:{type:'BOOLEAN',description:'Solo ingresos/gastos: true plantillas recurrentes; false historial realizado; omitido ambos separados en totales'}},required:['resource']}};
const aggregateSchema=z.object({resource:z.enum(resources),from:z.iso.date().optional(),to:z.iso.date().optional(),q:z.string().max(120).optional(),amount_min:z.coerce.number().min(0).optional(),amount_max:z.coerce.number().min(0).optional(),project_id:z.number().int().positive().optional(),recurring:z.boolean().optional()}).strict();
export const AGGREGATE_TOOL={name:'resumir_finanzas',description:'Suma, cuenta, promedia y da el mínimo/máximo de los registros del usuario autenticado que cumplan el filtro, sin traer cada fila: ideal para preguntas como "cuánto gasté en...", "cuántos ingresos tuve...", sobre todo en historiales largos donde listar filas con consultar_finanzas gastaría demasiado contexto. Los resultados son agregados completos de SQL sobre todo el filtro, nunca una muestra ni una estimación. Si el recurso tiene montos en más de una moneda (solo puede pasar en earnings), el resultado se desglosa por moneda: conviértelos con convertir_moneda antes de sumarlos entre sí, nunca los sumes directamente.',parameters:{type:'OBJECT',properties:{resource:{type:'STRING',enum:[...resources]},from:{type:'STRING',description:'Fecha inicial YYYY-MM-DD'},to:{type:'STRING',description:'Fecha final YYYY-MM-DD'},q:{type:'STRING',description:'Texto en descripción o etiquetas'},amount_min:{type:'NUMBER',description:'Solo montos mayores o iguales a este valor'},amount_max:{type:'NUMBER',description:'Solo montos menores o iguales a este valor'},project_id:{type:'INTEGER'},recurring:{type:'BOOLEAN',description:'Solo ingresos/gastos: true plantillas recurrentes; false historial realizado; omitido ambos'}},required:['resource']}};
const calculatorSchema=z.object({amount:amountSchema,currency:currencySchema,target:z.enum(['usd','bs']).default('usd'),date:z.iso.date().optional()}).strict();
export const CALCULATOR_TOOL={name:'convertir_moneda',description:'Convierte un importe a USD al valor del dólar paralelo, o directamente a bolívares a la tasa paralelo, usando la misma calculadora y tasas del conversor de Financy (fuente de verdad para tasas BCV y paralelo, no un dato inventado). Si el usuario pide el resultado en bolívares, usa target="bs" en una sola llamada; no lo calcules tú mismo encadenando el resultado en USD, eso pierde precisión y es innecesario. Úsala para preguntas como "cuántos son 543 euros a BCV" o "a cuánto equivalen 2000 bolívares".',parameters:{type:'OBJECT',properties:{amount:{type:'NUMBER',description:'Importe a convertir, en la moneda de origen'},currency:{type:'STRING',enum:['$','bs','$bcv','€','EUR_PARALLEL'],description:'Moneda y tasa de origen: $ dólares; bs bolívares a tasa paralelo; $bcv dólares a tasa BCV; € euros a tasa BCV; EUR_PARALLEL euros a tasa paralelo'},target:{type:'STRING',enum:['usd','bs'],description:'Moneda de salida: "usd" (por defecto, dólares a tasa paralelo) o "bs" (bolívares a tasa paralelo, directo, sin pasar por USD)'},date:{type:'STRING',description:'Fecha YYYY-MM-DD opcional; si se omite usa la tasa vigente'}},required:['amount','currency']}};
const reportSchema=z.object({kind:z.enum(['earnings','expenses']),from:z.iso.date().optional(),to:z.iso.date().optional(),q:z.string().max(200).optional(),provider:z.enum(['box','savings']).optional(),amount_min:z.coerce.number().min(0).optional(),amount_max:z.coerce.number().min(0).optional(),page:z.number().int().min(1).max(10000).default(1)}).strict();
export const REPORT_TOOL={name:'generar_reporte',description:'Genera un reporte de ingresos o gastos ya realizados (no plantillas recurrentes) con el mismo generador de la página Reportes de la app: mismos filtros de cuenta, fecha, texto/etiquetas y monto, y el mismo total exacto que vería el usuario ahí. Úsala para pedidos de reporte o desglose de un período o categoría concretos. Después de mostrar el resumen, dile al usuario que puede abrir report_url en Financy para ver el listado completo, exportarlo a CSV o imprimirlo.',parameters:{type:'OBJECT',properties:{kind:{type:'STRING',enum:['earnings','expenses'],description:'Ingresos o gastos'},from:{type:'STRING',description:'Fecha inicial YYYY-MM-DD'},to:{type:'STRING',description:'Fecha final YYYY-MM-DD'},q:{type:'STRING',description:'Texto en descripción o etiquetas'},provider:{type:'STRING',enum:['box','savings'],description:'Filtrar por cuenta: caja o ahorros'},amount_min:{type:'NUMBER',description:'Solo montos mayores o iguales a este valor'},amount_max:{type:'NUMBER',description:'Solo montos menores o iguales a este valor'},page:{type:'INTEGER',description:'Página de 20 filas; usa resumir_finanzas si solo necesitas el total'}},required:['kind']}};
@Injectable()
export class FinancialContextService {
  constructor(@Inject(Database) private db:Database,@Inject(RatesService) private rates:RatesService,@Inject(FinanceService) private finance:FinanceService){}
  async report(user:string,args:unknown){
    const v=parse(reportSchema,args);
    const {kind,...filters}=v;
    const result=await this.finance.list(user,kind,filters,true);
    const params=new URLSearchParams({mode:'history'});
    if(filters.q)params.set('q',filters.q);
    if(filters.provider)params.set('provider',filters.provider);
    if(filters.from)params.set('from',filters.from);
    if(filters.to)params.set('to',filters.to);
    return {...result,kind,report_url:'/reports?kind='+kind+'&'+params.toString(),notes:'items es una muestra de hasta 20 filas de esta página; total y totalAmount ya son el conteo y la suma exactos de todo el filtro (no solo de la muestra). Para el listado completo, exportar a CSV o imprimir, indica al usuario que abra report_url dentro de Financy.'};
  }
  async convert(args:unknown){
    const v=parse(calculatorSchema,args);
    const result=v.target==='bs'?await this.rates.toBs(v.currency,v.amount,v.date):await this.rates.convert(v.currency,v.amount,v.date);
    return {amount:v.amount,currency:v.currency,target:v.target,result,unit:v.target==='bs'?'Bs':'USD',date:v.date??now().toISODate()};
  }
  async snapshot(user:string){
    return this.db.transaction(async sql=>{
      await sql.query('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');
      const profile=(await sql.query('SELECT name,monthly_expense_limit FROM users WHERE id=$1',[user])).rows[0];
      const accounts:any={};for(const t of ['boxes','savings'])accounts[t]=(await sql.query(`SELECT id,amount FROM ${t} WHERE "user"=$1 ORDER BY id`,[user])).rows;
      const totals:any={};for(const t of ['earnings','expenses'])totals[t]=(await sql.query(`SELECT project_id,provider,${t==='earnings'?'currency':"'$'"} AS currency, (term IS NOT NULL OR claim_day IS NOT NULL) AS recurring,count(*) AS count,COALESCE(sum(amount),0) AS amount,min(created_at) AS first_date,max(created_at) AS last_date FROM ${t} WHERE "user"=$1 GROUP BY project_id,provider,${t==='earnings'?'currency,':''}(term IS NOT NULL OR claim_day IS NOT NULL) ORDER BY project_id NULLS FIRST LIMIT 101`,[user])).rows;
      const months=(await sql.query(`SELECT month,type,sum(amount) AS amount,count(*) AS count FROM (SELECT to_char(created_at,'YYYY-MM') AS month,'income' AS type,amount FROM earnings WHERE "user"=$1 AND project_id IS NULL AND term IS NULL AND claim_day IS NULL UNION ALL SELECT to_char(created_at,'YYYY-MM') AS month,'expense' AS type,amount FROM expenses WHERE "user"=$1 AND project_id IS NULL AND term IS NULL AND claim_day IS NULL) h GROUP BY month,type ORDER BY month DESC LIMIT 24`,[user])).rows;
      const shopping=(await sql.query('SELECT status,not_discount,count(*) AS count,COALESCE(sum(amount),0) AS amount FROM shop_list_items WHERE "user"=$1 GROUP BY status,not_discount',[user])).rows;
      const currentBudgets=await this.queryWith(sql,user,{resource:'budgets',from:now().startOf('month').toISODate()!,to:now().endOf('month').toISODate()!,page:1});
      return {as_of:now().toISO(),timezone:'America/Caracas',profile,accounts,all_time_totals:totals,totals_groups_truncated:Object.values(totals).some((v:any)=>v.length>100),recent_months:months,recent_months_limit:24,shopping,current_budgets:currentBudgets,notes:'Saldos actuales son la fuente de verdad. No se reconstruyen sumando historial: hay transferencias y saldos importados. Totales agrupados: máximo 101 grupos; usa herramientas para desgloses adicionales. Meses limitados a 24 grupos mes/tipo; no es todo el historial. Plantillas recurrentes no son movimientos realizados. No sumar distintas monedas. Datos personales y de proyectos separados.'};
    });
  }
  async query(user:string,args:unknown){const v=parse(querySchema,args);return this.db.transaction(async sql=>{await sql.query('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');return this.queryWith(sql,user,v);});}
  private async queryWith(sql:Sql,user:string,v:z.infer<typeof querySchema>){
    const params:any[]=[user];let source='',where='',columns='',date='',search='',group='';
    if(v.resource==='earnings'||v.resource==='expenses'){
      source=v.resource+' e';where='e."user"=$1';date='e.created_at';search="e.description || ' ' || COALESCE(e.slug,'')";
      columns=`e.id,e.description,e.amount,e.provider,e.project_id,e.slug,e.term,e.claim_day,e."UpdatedTerm",e."NextClaim",e.recurrence_type,e.auto_claim,e.recurring_id,e.created_at,${v.resource==='earnings'?'e.currency':"'$' AS currency,e.shop_list_item_id"}`;
      group=`e.project_id,e.provider,${v.resource==='earnings'?'e.currency':"'$'::text"},(e.term IS NOT NULL OR e.claim_day IS NOT NULL)`;
    }else if(v.resource==='shopping'){source='shop_list_items e';where='e."user"=$1';date='e.created_at';search='e.description';columns='e.id,e.description,e.amount,e.status,e.provider,e.not_discount,e.created_at';}
    else if(v.resource==='budgets'){source='budget_categories e JOIN monthly_budgets b ON b.id=e.monthly_budget_id';where='b.user_id=$1';date='b.month';search="e.name || ' ' || e.slug";columns='e.id,e.name,e.slug,e.amount,b.month';}
    else if(v.resource==='splits'){source='expense_splits e JOIN expenses x ON x.id=e.expense_id';where='x."user"=$1';date='e.created_at';search='x.description';columns='e.expense_id,e.amount,e.paid_amount,e.status,x.description,x.project_id';}
    else if(v.resource==='allocations'){source="financy_allocations e JOIN (SELECT id,'earnings' AS kind,\"user\",description,created_at FROM earnings UNION ALL SELECT id,'expenses' AS kind,\"user\",description,created_at FROM expenses) x ON x.id=e.reference_id AND x.kind=e.kind";where='x."user"=$1';date='x.created_at';search='x.description';columns='e.kind,e.reference_id,e.box,e.savings,x.description,x.created_at';}
    else{source='movements e';where='e."user"=$1';date='e.created_at';search='e.description';columns='e.id,e.type,e.description,e.amount,e.provider,e.project_id,e.reference_id,e.created_at';}
    const add=(condition:string,value:any)=>{params.push(value);where+=' AND '+condition.replace('?',`$${params.length}`);};
    if(v.from)add(`${date}>=?::date`,v.from);if(v.to)add(`${date}<?::date+interval '1 day'`,v.to);if(v.q)add(`lower(${search}) LIKE ?`,'%'+v.q.toLowerCase()+'%');
    if(v.amount_min!==undefined){if(v.resource==='allocations')return {error:'Este recurso no tiene un monto único; usa box/savings.'};add('e.amount>=?',v.amount_min);}
    if(v.amount_max!==undefined){if(v.resource==='allocations')return {error:'Este recurso no tiene un monto único; usa box/savings.'};add('e.amount<=?',v.amount_max);}
    if(v.project_id!==undefined){if(!['earnings','expenses','movements','splits'].includes(v.resource))return {error:'Este recurso no tiene proyectos'};add(`${v.resource==='splits'?'x':'e'}.project_id=?`,v.project_id);}
    if(v.recurring!==undefined){if(!['earnings','expenses'].includes(v.resource))return {error:'Solo ingresos y gastos tienen recurrencias'};where+=v.recurring?' AND (e.term IS NOT NULL OR e.claim_day IS NOT NULL)':' AND e.term IS NULL AND e.claim_day IS NULL';}
    const total=(await sql.query(`SELECT count(*) AS count ${v.resource==='allocations'?'':',COALESCE(sum(e.amount),0) AS amount'} FROM ${source} WHERE ${where}`,params)).rows[0];
    let totals:any=null;
    if(group)totals=(await sql.query(`SELECT e.project_id,e.provider,${v.resource==='earnings'?'e.currency':"'$'::text AS currency"},(e.term IS NOT NULL OR e.claim_day IS NOT NULL) AS recurring, sum(e.amount) AS amount,count(*) AS count FROM ${source} WHERE ${where} GROUP BY ${group} LIMIT 101`,params)).rows;
    const rows=(await sql.query(`SELECT ${columns} FROM ${source} WHERE ${where} ORDER BY ${date} DESC,e.${v.resource==='allocations'?'reference_id':'id'} DESC LIMIT 30 OFFSET $${params.length+1}`,[...params,(v.page-1)*30])).rows;
    return {as_of:now().toISO(),resource:v.resource,filter:v,total:Number(total.count),totals:totals??{amount:v.resource==='allocations'?null:total.amount},totals_groups_truncated:totals?.length>100,page:v.page,pages:Math.ceil(Number(total.count)/30),rows:rows.map(r=>({...r,...(group?{due_at:dueAt(r)?.toISO()??null}:{})})),notes:v.resource==='movements'?'Registro legado: puede incluir plantillas antiguas; para totales usa earnings/expenses recurrent=false.':v.resource==='budgets'?'amount es el límite de la categoría. Consulta gastos históricos del mes y etiquetas para calcular consumo; una misma etiqueta puede pertenecer a más de una categoría.':v.resource==='allocations'?'Solo movimientos creados por NestJS tienen distribución exacta.':''};
  }
  async aggregate(user:string,args:unknown){const v=parse(aggregateSchema,args);return this.db.transaction(async sql=>{await sql.query('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');return this.aggregateWith(sql,user,v);});}
  private async aggregateWith(sql:Sql,user:string,v:z.infer<typeof aggregateSchema>){
    if(v.resource==='allocations')return {error:'Este recurso no tiene un monto único agregable (usa box y savings por separado); consulta consultar_finanzas para inspeccionarlo movimiento por movimiento.'};
    const params:any[]=[user];let source='',where='',date='',search='',currency='';
    if(v.resource==='earnings'||v.resource==='expenses'){
      source=v.resource+' e';where='e."user"=$1';date='e.created_at';search="e.description || ' ' || COALESCE(e.slug,'')";currency=v.resource==='earnings'?'e.currency':"'$'::text";
    }else if(v.resource==='shopping'){source='shop_list_items e';where='e."user"=$1';date='e.created_at';search='e.description';currency="'$'::text";}
    else if(v.resource==='budgets'){source='budget_categories e JOIN monthly_budgets b ON b.id=e.monthly_budget_id';where='b.user_id=$1';date='b.month';search="e.name || ' ' || e.slug";currency="'$'::text";}
    else if(v.resource==='splits'){source='expense_splits e JOIN expenses x ON x.id=e.expense_id';where='x."user"=$1';date='e.created_at';search='x.description';currency="'$'::text";}
    else{source='movements e';where='e."user"=$1';date='e.created_at';search='e.description';currency="'$'::text";}
    const add=(condition:string,value:any)=>{params.push(value);where+=' AND '+condition.replace('?',`$${params.length}`);};
    if(v.from)add(`${date}>=?::date`,v.from);if(v.to)add(`${date}<?::date+interval '1 day'`,v.to);if(v.q)add(`lower(${search}) LIKE ?`,'%'+v.q.toLowerCase()+'%');
    if(v.amount_min!==undefined)add('e.amount>=?',v.amount_min);
    if(v.amount_max!==undefined)add('e.amount<=?',v.amount_max);
    if(v.project_id!==undefined){if(!['earnings','expenses','movements','splits'].includes(v.resource))return {error:'Este recurso no tiene proyectos'};add(`${v.resource==='splits'?'x':'e'}.project_id=?`,v.project_id);}
    if(v.recurring!==undefined){if(!['earnings','expenses'].includes(v.resource))return {error:'Solo ingresos y gastos tienen recurrencias'};where+=v.recurring?' AND (e.term IS NOT NULL OR e.claim_day IS NOT NULL)':' AND e.term IS NULL AND e.claim_day IS NULL';}
    const rows=(await sql.query(`SELECT ${currency} AS currency,count(*) AS count,COALESCE(sum(e.amount),0) AS sum,COALESCE(avg(e.amount),0) AS avg,COALESCE(min(e.amount),0) AS min,COALESCE(max(e.amount),0) AS max FROM ${source} WHERE ${where} GROUP BY ${currency}`,params)).rows;
    const by_currency=rows.map(r=>({currency:r.currency,count:Number(r.count),sum:money(r.sum),avg:money(r.avg),min:money(r.min),max:money(r.max)}));
    return {as_of:now().toISO(),resource:v.resource,filter:v,total_count:by_currency.reduce((n,r)=>n+r.count,0),by_currency,notes:by_currency.length>1?'Hay montos en más de una moneda: conviértelos con convertir_moneda antes de sumarlos entre sí, nunca los sumes directamente.':''};
  }
}
